name: Distribution Builds

on:
  push:
  # Manual dispatch for testing
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: |
          rustup target add i686-pc-windows-msvc
          cargo build --release
          cargo build --target i686-pc-windows-msvc --release
          mkdir out
          copy target/release/roast.exe target/release/roast-win-64.exe
          copy target/i686-pc-windows-msvc/release/roast.exe target/i686-pc-windows-msvc/release/roast-win-32.exe
          Compress-Archive -Path target/release/roast-win-64.exe -Destination out/roast-win-64.exe.zip
          Compress-Archive -Path target/i686-pc-windows-msvc/release/roast-win-32.exe -Destination out/roast-win-32.exe.zip
      - name: Build MacOS
        if: matrix.os == 'macos-latest'
        run: |
          rustup target add aarch64-apple-darwin
          cargo build --release
          cargo build --target aarch64-apple-darwin --release
          mkdir -p out
          mv target/release/roast ./roast-macos-x86_64
          mv target/aarch64-apple-darwin/release/roast ./roast-macos-aarch64
          chmod +x ./roast-macos-x86_64 ./roast-macos-aarch64
          zip out/roast-macos-x86_64.zip ./roast-macos-x86_64
          zip out/roast-macos-aarch64.zip ./roast-macos-aarch64
      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install -y gcc-aarch64-linux-gnu
          rustup target add aarch64-unknown-linux-gnu
          cargo build --release
          cargo build --target aarch64-unknown-linux-gnu --release
          mkdir -p out
          chmod +x out/roast-linux-x86_64 out/roast-linux-aarch64
          mv target/release/roast ./roast-linux-x86_64
          mv target/aarch64-unknown-linux-gnu/release/roast ./roast-linux-aarch64
          chmod +x ./roast-linux-x86_64 ./roast-linux-aarch64
          zip out/roast-linux-x86_64.zip ./roast-linux-x86_64
          zip out/roast-linux-aarch64.zip ./roast-linux-aarch64
      - name: Artifact upload
        uses: actions/upload-artifact@v3
        with:
          name: outputs
          path: out
          retention-days: 1
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: out/*
