name: Distribution Builds

on:
  # Manual dispatch for testing
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release
      - name: Add arm binaries
        if: matrix.os == 'macos-latest'
        run: |
          rustup target add aarch64-apple-darwin
          cargo build --target aarch64-apple-darwin --release
        # with:
          # files: ${{ matrix.releaseFiles }}
      - name: Artifact upload
        uses: actions/upload-artifact@v3
      #   # Enable to check run output, keep disabled as it takes a lot of space and time
      #   if: false
        with:
          name: outputs
          path: |
            target/release
            target/aarch64-apple-darwin/release
          retention-days: 1
